spring.application.name=PortfolioBackend

spring.datasource.url=jdbc:postgresql://dpg-d7h0sgdckfvc739n63qg-a.singapore-postgres.render.com:5432/my_database_eimn
spring.datasource.username=my_database_eimn_user
spring.datasource.password=zEJuUDJygzMU8Qi81C1WvVix5wbe8yHZ


spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true




spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=slshree321@gmail.com
spring.mail.password=nges kjrw sdjd rwem
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true